version: "3.8"
services:
  dbblitz:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
    volumes:
      - dbpg:/var/lib/postgresql/data
    restart: always

  blitzblog:
    build: .
    restart: always
    ports:
      - 3003:3000
    volumes:
      - ./app :/app

volumes:
  dbpg:
